export const Menus = [
    {
        id: '94298',
        name: '3 Chicken Wings',
        position: 1,
        description: 'Tender, Spicy and Juicy. Original or Peri-Crusted',
        images: 'https://i0.wp.com/dwardcooks.com/wp-content/uploads/2021/11/IMG_1536-scaled.jpg?w=610&ssl=1',
        price: '250.00',
        cuisine_name: 'Indian',
        category_name: 'Appetizers',
    },
    {
        id: '94301',
        name: 'Chicken Livers and Portuguese Roll',
        position: 2,
        description:
            'Chicken Livers Topped with PERi-PERi Sauce, Served with A Roll To Soak Up The Sauce',
        images: [],
        price: '250.00',
        cuisine_name: 'Indian',
        category_name: 'Appetizers',
    },
    {
        id: '94304',
        name: 'Spicy Mixed Olives (V)',
        position: 3,
        description: 'Co-Starring Garlic, Pepper and Chili',
        images: [],
        price: '215.00',
        cuisine_name: 'Indian',
        category_name: 'Appetizers',
    },
    {
        id: '94307',
        name: 'Hummus with PERI-PERI Drizzle (V)',
        position: 4,
        description:
            'Pour Smoky PERi-PERi Oil Over Creamy Hummus and Dig in with Strips Of Warm Pita',
        images: [],
        price: '215.00',
        consumable: '1:1',
        cuisine_name: 'Indian',
        category_name: 'Appetizers',
    },
    {
        id: '94310',
        name: 'Red Pepper Dip (V)',
        position: 5,
        description:
            'Dive Into Temping Roasted Red Pepper and Chili Spice Dip with Warm Pita Strips',
        images: [],
        price: '205.00',
        consumable: '1:1',
        cuisine_name: 'Indian',
        category_name: 'Appetizers',
    },
    {
        id: '94313',
        name: 'Appetizers Platter',
        position: 6,
        description: 'Choose any Three Appetizers',
        images: [],
        price: '615.00',
        consumable: '1:1',
        cuisine_name: 'Indian',
        category_name: 'Appetizers',
    },
    {
        id: '94316',
        name: 'All Together Now (V)',
        position: 7,
        description:
            'Spicy Mixed Olives, Red Pepper Dip, Hummus with PERi-PERi Drizzle and Warm Pita Strips',
        images: [],
        price: '520.00',
        consumable: '1:1',
        cuisine_name: 'Indian',
        category_name: 'Appetizers',
    },
];
